name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, amd64v3]
        os: [[linux, ""], [darwin, ""], [windows, ".exe"]]
        cmd: [client, server]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.0'

    - name: Build
      run: |
        make ${{ matrix.os[0] }}
        if [ ${{ matrix.os[0] }} != "darwin" ]; then
          upx --lzma --best ${{ matrix.cmd }}_${{ matrix.os[0] }}_${{ matrix.arch }}${{ matrix.os[1] }}
        fi

    - name: upload_${{ matrix.cmd }}_${{ matrix.os[0] }}_${{ matrix.arch }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.cmd }}_${{ matrix.os[0] }}_${{ matrix.arch }}
        path: |
          ${{ matrix.cmd }}_${{ matrix.os[0] }}_${{ matrix.arch }}${{ matrix.os[1] }}